name: Sync Backend to Subtree Branch

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"

jobs:
  sync-backend:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Git
      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      # Fetch the latest changes from the backend subtree branch
      - name: Fetch remote changes from backend branch
        run: |
          git fetch origin backend

      # Merge the remote changes to ensure we are up-to-date with the remote backend branch
      - name: Merge changes from backend branch
        run: |
          git checkout backend || git checkout -b backend
          git merge origin/backend --no-edit

      # Push the changes from the backend folder to the backend subtree branch
      - name: Push changes from backend folder to backend subtree branch
        run: |
          git subtree push --prefix=backend origin main:backend
